# Generated by Django 6.1.2 on 2026-10-07 00:22

import apps.cuentas.models
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('correo', models.EmailField(error_messages={'unique': 'Ya existe un usuario con esa dirección de correo electrónico.'}, max_length=254, unique=True, verbose_name='correo electrónico')),
                ('nombre', models.CharField(blank=True, max_length=150, verbose_name='nombre')),
                ('apellidos', models.CharField(blank=True, max_length=150, verbose_name='apellidos')),
                ('is_staff', models.BooleanField(default=False, help_text='Indica si el usuario puede entrar al sitio de administración.', verbose_name='acceso al sitio de administración')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el usuario puede iniciar sesión. Para dar de baja una cuenta se desmarca esta opción en lugar de eliminarla.', verbose_name='activo')),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de alta')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('correo'), name='cuentas_usuario_correo_unico', violation_error_message='Ya existe un usuario con esa dirección de correo electrónico.')],
            },
            managers=[
                ('objects', apps.cuentas.models.GestorUsuarios()),
            ],
        ),
    ]
