"""Pruebas de scripts/revisar_commit.py: símbolos, atribuciones, mensajes de commit,
identidad, lectura de diffs y revisión con Ruff.

Los emojis y símbolos se escriben con su nombre Unicode (``\\N{...}``) para que este archivo
no los contenga literalmente.
"""

from django.test import SimpleTestCase

from scripts.revisar_commit import (
    LARGO_MAXIMO_PRIMERA_LINEA,
    LINEA_DE_CORTE,
    buscar_simbolos,
    es_atribucion,
    extraer_lineas_agregadas,
    revisar_identidad,
    revisar_lineas,
    revisar_mensaje,
    revisar_python,
)

TEXTO_EN_ESPANOL = "¿Cómo se valida el año? Señal, pingüino, «comillas» y —rayas—."
IDENTIDAD_PERSONA = "Persona Ejemplo <persona@example.com> 1791000000 -0600"


class PruebasSimbolos(SimpleTestCase):
    def test_texto_en_espanol_no_tiene_simbolos(self):
        self.assertEqual(buscar_simbolos(TEXTO_EN_ESPANOL), [])

    def test_detecta_emojis_marcas_estrellas_y_flechas(self):
        texto = (
            "\N{ROCKET} \N{CHECK MARK} \N{BLACK STAR} \N{RIGHTWARDS ARROW} "
            "\N{WHITE HEAVY CHECK MARK}\N{VARIATION SELECTOR-16}"
        )
        self.assertEqual(
            buscar_simbolos(texto),
            ["U+1F680", "U+2713", "U+2605", "U+2192", "U+2705", "U+FE0F"],
        )

    def test_no_repite_un_simbolo(self):
        self.assertEqual(buscar_simbolos("\N{ROCKET}\N{ROCKET}"), ["U+1F680"])


class PruebasAtribucion(SimpleTestCase):
    def test_detecta_trailer_de_coautoria_de_un_asistente(self):
        self.assertTrue(es_atribucion("Co-authored-by: Claude <noreply@anthropic.com>"))

    def test_admite_trailer_de_coautoria_de_una_persona(self):
        self.assertFalse(es_atribucion("Co-authored-by: Persona Ejemplo <persona@example.com>"))

    def test_detecta_lineas_de_generacion_en_ingles_y_espanol(self):
        for linea in (
            "Generated with [Claude Code](https://claude.com/claude-code)",
            "# Created by ChatGPT",
            "Código generado con IA.",
            "Escrito con ayuda de Copilot.",
        ):
            with self.subTest(linea=linea):
                self.assertTrue(es_atribucion(linea))

    def test_detecta_enlace_a_una_sesion(self):
        self.assertTrue(es_atribucion("Sesión: https://claude.ai/code/session_ejemplo"))

    def test_admite_textos_sin_atribucion(self):
        for linea in (
            "# Generated by Django 6.1 on 2026-10-07 12:00",
            "Paginar la lista con un cursor de la base de datos.",
            TEXTO_EN_ESPANOL,
        ):
            with self.subTest(linea=linea):
                self.assertFalse(es_atribucion(linea))


class PruebasRevisarLineas(SimpleTestCase):
    def test_informa_ruta_y_numero_de_linea(self):
        problemas = revisar_lineas("README.md", [(7, "Listo \N{ROCKET}")])
        self.assertEqual(problemas, ["README.md:7: emojis o símbolos usados como íconos: U+1F680"])

    def test_informa_atribucion_en_un_archivo(self):
        problemas = revisar_lineas("apps/modulo.py", [(1, '"""Generated by Copilot."""')])
        self.assertEqual(problemas, ["apps/modulo.py:1: atribución a una herramienta de IA"])

    def test_documentos_de_las_reglas_pueden_citar_atribuciones(self):
        problemas = revisar_lineas(
            "docs/lineamientos/autoria-y-redaccion.md",
            [(1, "Co-authored-by: Claude <noreply@anthropic.com>")],
        )
        self.assertEqual(problemas, [])

    def test_documentos_de_las_reglas_no_pueden_tener_simbolos(self):
        problemas = revisar_lineas("CLAUDE.md", [(1, "\N{CHECK MARK} Regla")])
        self.assertEqual(len(problemas), 1)


class PruebasMensaje(SimpleTestCase):
    def test_mensaje_correcto_no_tiene_problemas(self):
        mensaje = "Validar el año de la factura\n\nEl año futuro se rechaza.\n"
        self.assertEqual(revisar_mensaje(mensaje), [])

    def test_rechaza_primera_linea_larga(self):
        largo = LARGO_MAXIMO_PRIMERA_LINEA + 1
        problemas = revisar_mensaje("a" * largo)
        self.assertEqual(
            problemas,
            [f"La primera línea tiene {largo} caracteres; el máximo es 72."],
        )

    def test_rechaza_trailer_de_coautoria(self):
        mensaje = "Validar el año\n\nCo-authored-by: Claude <noreply@anthropic.com>\n"
        self.assertEqual(
            revisar_mensaje(mensaje),
            ["Línea 3: atribución a una herramienta de IA."],
        )

    def test_rechaza_emojis(self):
        problemas = revisar_mensaje("Validar el año \N{SPARKLES}")
        self.assertEqual(problemas, ["Línea 1: emojis o símbolos usados como íconos: U+2728"])

    def test_ignora_comentarios_y_el_diff_de_commit_verbose(self):
        mensaje = (
            "Validar el año\n"
            "# Comentario de Git con \N{ROCKET}\n"
            f"{LINEA_DE_CORTE}\n"
            "+Co-authored-by: Claude <noreply@anthropic.com>\n"
        )
        self.assertEqual(revisar_mensaje(mensaje), [])

    def test_mensaje_vacio_lo_cancela_git(self):
        self.assertEqual(revisar_mensaje("# Solo comentarios\n\n"), [])


class PruebasIdentidad(SimpleTestCase):
    def test_admite_persona_y_rama_del_proyecto(self):
        problemas = revisar_identidad(
            IDENTIDAD_PERSONA,
            IDENTIDAD_PERSONA,
            "feature/paginacion-por-cursor",
        )
        self.assertEqual(problemas, [])

    def test_rechaza_autor_que_es_una_herramienta(self):
        problemas = revisar_identidad(
            "Claude <noreply@anthropic.com> 1791000000 -0600",
            IDENTIDAD_PERSONA,
            "feature/facturas",
        )
        self.assertEqual(len(problemas), 1)
        self.assertIn("autor", problemas[0])

    def test_rechaza_committer_bot(self):
        problemas = revisar_identidad(
            IDENTIDAD_PERSONA,
            "ejemplo[bot] <bot@example.com> 1791000000 -0600",
            "feature/facturas",
        )
        self.assertEqual(len(problemas), 1)
        self.assertIn("committer", problemas[0])

    def test_rechaza_rama_con_el_nombre_de_una_herramienta(self):
        problemas = revisar_identidad(IDENTIDAD_PERSONA, IDENTIDAD_PERSONA, "claude/facturas")
        self.assertEqual(
            problemas,
            ["El nombre de la rama claude/facturas menciona una herramienta de IA."],
        )


class PruebasDiff(SimpleTestCase):
    def test_extrae_lineas_agregadas_con_su_numero(self):
        diff = (
            "diff --git a/README.md b/README.md\n"
            "--- a/README.md\n"
            "+++ b/README.md\n"
            "@@ -3,0 +4,2 @@ encabezado\n"
            "+primera\n"
            "+segunda\n"
            "@@ -10 +12 @@\n"
            "-anterior\n"
            "+reemplazo\n"
            "diff --git a/docs/nuevo.md b/docs/nuevo.md\n"
            "new file mode 100644\n"
            "--- /dev/null\n"
            "+++ b/docs/nuevo.md\n"
            "@@ -0,0 +1 @@\n"
            "+++ texto que empieza con signos de suma\n"
        )
        self.assertEqual(
            extraer_lineas_agregadas(diff),
            {
                "README.md": [(4, "primera"), (5, "segunda"), (12, "reemplazo")],
                "docs/nuevo.md": [(1, "++ texto que empieza con signos de suma")],
            },
        )


class PruebasRuff(SimpleTestCase):
    def test_contenido_correcto_no_tiene_problemas(self):
        self.assertEqual(revisar_python("apps/ejemplo.py", b'VALOR = "texto"\n'), [])

    def test_informa_reglas_incumplidas(self):
        problemas = revisar_python("apps/ejemplo.py", b"import os\n")
        self.assertTrue(any("F401" in problema for problema in problemas))

    def test_informa_formato_pendiente(self):
        problemas = revisar_python("apps/ejemplo.py", b"VALOR=1\n")
        self.assertEqual(
            problemas,
            ["apps/ejemplo.py: falta aplicar el formato: python -m ruff format apps/ejemplo.py"],
        )

    def test_omite_las_migraciones(self):
        problemas = revisar_python("apps/ejemplo/migrations/0002_ejemplo.py", b"import os\n")
        self.assertEqual(problemas, [])
